/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Head from "next/head";
import { useFirestore, useFirestoreCollectionData } from "reactfire";
import { collection } from "firebase/firestore";
import {
  Link,
  Table,
  TableBody,
  TableCell,
  TableColumn,
  TableHeader,
  TableRow,
} from "@nextui-org/react";

export default function Home() {
  const firestore = useFirestore();
  const ref = collection(firestore, "registrations");
  const { status, data } = useFirestoreCollectionData(ref);

  const columns = [
    "NAME",
    "NICKNAME",
    "EMAIL",
    "CONTACT",
    "DOB",
    "INVITED BY",
    "SATELLITE",
    "PASTORAL TEAM",
  ];

  console.log(data);
  return (
    <>
      <Head>
        <title>Admin | Registration</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/fga.png" />
      </Head>

      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c] px-4 py-16 dark">
        {status === "success" ? (
          <Table
            isCompact
            className="text-white"
            aria-label="Table"
            selectionMode="multiple"
          >
            <TableHeader>
              {columns.map((c) => (
                <TableColumn allowsSorting key={c}>
                  {c}
                </TableColumn>
              ))}
            </TableHeader>
            <TableBody>
              {data.map((d) => (
                <TableRow key={d.user_id}>
                  <TableCell>{`${d["full_name_as_per_IC_(en)"]} | ${d["full_name_(chi)"]}`}</TableCell>
                  <TableCell className={d.nickname ? "" : "text-gray-500"}>
                    {d.nickname ?? "N/A"}
                  </TableCell>
                  <TableCell>{d.email}</TableCell>
                  <TableCell>
                    <Link href={`tel:${d.contact_no}`}>
                      {String(d.contact_no).replace("-", "")}
                    </Link>
                  </TableCell>
                  <TableCell>
                    {new Date(d.date_of_birth as string).toLocaleDateString(
                      "en-US",
                      {
                        dateStyle: "long",
                      },
                    )}
                  </TableCell>
                  <TableCell>
                    {d.invited_by === "Ministry"
                      ? `${d.invited_by} | ${d.ministry_team}`
                      : d.invited_by}
                  </TableCell>
                  <TableCell>{d.service_location}</TableCell>
                  <TableCell>{d.pastoral_team}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : (
          <div>Loading</div>
        )}
      </main>
    </>
  );
}
